[package]
name = "malva"
version = "0.1.0"
edition = "2021"
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Configurable, smart and fast CSS/SCSS/Sass/Less formatter."
repository = "https://github.com/g-plane/malva"
license = "MIT"
exclude = ["/tests"]

[dependencies]
aho-corasick = "1.1"
itertools = "0.11"
memchr = "2.6"
raffia = "0.7"
serde = { version = "1.0", optional = true }
tiny_pretty = "0.1"

[dev-dependencies]
insta = { version = "1.38", features = ["glob"] }
toml = "0.7"

[features]
config_serde = ["raffia/config_serde", "serde"]
